when:
  - event: push
    branch: main
  - event: push
    branch: '*'
  - event: cron
  - event: manual

steps:
  - name: build
    image: node:24
    commands:
      - corepack enable
      - export PUBLIC_COMMIT_HASH=$(git rev-parse --short HEAD)
      - pnpm i --frozen-lockfile
      - OBSIDIAN_CONTENT_ROOT="/publish-blog" pnpm run build
    volumes:
      - /appdata/syncthing/syncthing/Syncthing Root/KennethPersonal/Personal/Writing/PersonalSite/Publish:/publish-blog

  - name: deploy
    image: node:24
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: cloudflare_api_token
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: cloudflare_account_id
    commands:
      - BRANCH=${CI_COMMIT_SOURCE_BRANCH:-${CI_COMMIT_BRANCH}}
      - BRANCH="${BRANCH}${PREVIEW:-}"
      - corepack enable
      - npx wrangler pages deploy ./dist
          --project-name=kennethchristensen
          --branch="$BRANCH"
