when:
  - event: push
    branch: main
  - event: push
    branch: '*'
  - event: cron
  - event: manual

steps:
  - name: build
    image: node:20
    commands:
      - corepack enable
      - export PUBLIC_COMMIT_HASH=$(git rev-parse --short HEAD)
      - pnpm i --frozen-lockfile
      - pnpm run build

  - name: deploy
    image: node:20
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: cloudflare_api_token
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: cloudflare_account_id
    commands:
      - BRANCH=${CI_COMMIT_SOURCE_BRANCH:-${CI_COMMIT_BRANCH}}
      - corepack enable
      - npx wrangler pages deploy ./dist
          --project-name=kennethchristensen
          --branch="$BRANCH"
